### ISSUE TITLE
did pro version ever come out?

### ISSUE THREAD

**Issue by ghost** [lukaspj/IPS-Lite-for-T3D#2]
I was interested in the pro version. Also do you have screenshots?

**Comment by lukaspj** [comment]
Hi @communityus
Yes, it came out in 2013 (a while ago).
I don't know if it works with latest version of T3D, but contact me on Discord or on my email and I will try and see if I can dig it up!

**Comment by ghost** [comment]
Thx. I will look for you on Torque discord.
